[program:uwtec-localizer]
command=/home/uwtec/USV/supervisor/uwtec_localizer.sh
user=uwtec
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/uwtec/USV/logs/uwtec_localizer.log

