[program:uwtec-twist-mux]
command=/home/uwtec/USV/supervisor/uwtec_twist_mux.sh
user=uwtec
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/uwtec/USV/logs/uwtec_twist_mux.log

