[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "*"

[package.host-dependencies] 
hatchling = "==1.26.3"
