[program:uwtec-navigator]
command=/home/uwtec/USV/usv_ws/supervisor/uwtec_navigator.sh
user=uwtec
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/uwtec/USV/usv_ws/log/uwtec_navigator.log

